import pandas as pd
import os

def get_vietnamese_meaning(word, word_type, definition):
    mapping = {
        "abandoned": "Bị bỏ rơi", "ability": "Khả năng", "able": "Có thể", "abolish": "Bãi bỏ", "abortion": "Sự phá thai",
        "about": "Về, khoảng", "above": "Ở trên", "abroad": "Ở nước ngoài", "absence": "Sự vắng mặt", "absent": "Vắng mặt",
        "absolute": "Tuyệt đối", "absolutely": "Chắc chắn", "absorb": "Hấp thụ", "abstract": "Trừu tượng", "absurd": "Vô lý",
        "abundance": "Sự phong phú", "abuse": "Lạm dụng", "academic": "Học thuật", "academy": "Học viện", "accelerate": "Tăng tốc",
        "accent": "Giọng, trọng âm", "accept": "Chấp nhận", "acceptable": "Chấp nhận được", "acceptance": "Sự chấp nhận", "access": "Truy cập",
        "accessible": "Có thể truy cập", "accident": "Tai nạn", "accidentally": "Vô tình", "accommodate": "Cung cấp chỗ ở", "accommodation": "Chỗ ở",
        "accompany": "Đi cùng", "accomplish": "Hoàn thành", "accomplishment": "Thành tựu", "accordance": "Sự phù hợp", "according to": "Theo",
        "accordingly": "Phù hợp", "account": "Tài khoản", "accountability": "Trách nhiệm giải trình", "accountable": "Chịu trách nhiệm",
        "accountant": "Kế toán", "accumulate": "Tích lũy", "accumulation": "Sự tích lũy", "accuracy": "Độ chính xác", "accurate": "Chính xác",
        "accurately": "Một cách chính xác", "accusation": "Sự cáo buộc", "accuse": "Buộc tội", "accused": "Bị cáo", "achieve": "Đạt được",
        "achievement": "Thành tích", "acid": "Axit", "acknowledge": "Thừa nhận", "acquire": "Có được", "acquisition": "Sự đạt được",
        "acre": "Mẫu Anh", "across": "Băng qua", "act": "Hành động", "action": "Hành động", "activate": "Kích hoạt", "activation": "Sự kích hoạt",
        "active": "Năng động", "activist": "Nhà hoạt động", "activity": "Hoạt động", "actor": "Diễn viên", "actress": "Nữ diễn viên",
        "actual": "Thực tế", "actually": "Thực sự", "acute": "Cấp tính", "ad": "Quảng cáo", "adapt": "Thích nghi", "adaptation": "Sự thích nghi",
        "add": "Thêm vào", "addiction": "Sự nghiện", "addition": "Sự thêm vào", "additional": "Bổ sung", "additionally": "Ngoài ra",
        "address": "Địa chỉ", "adequate": "Đầy đủ", "adequately": "Một cách đầy đủ", "adhere": "Tuân thủ", "adjacent": "Phụ cận",
        "adjust": "Điều chỉnh", "adjustment": "Sự điều chỉnh", "administer": "Quản lý", "administration": "Sự quản lý", "administrative": "Hành chính",
        "administrator": "Quản trị viên", "admire": "Ngưỡng mộ", "admission": "Sự nhận vào", "admit": "Thừa nhận", "adolescent": "Thanh thiếu niên",
        "adopt": "Nhận nuôi", "adoption": "Sự nhận nuôi", "adore": "Yêu mến", "adult": "Người lớn", "advance": "Tiến bộ", "advanced": "Nâng cao",
        "advantage": "Lợi thế", "adventure": "Phiêu lưu", "adverse": "Bất lợi", "advertise": "Quảng cáo", "advertisement": "Quảng cáo",
        "advertising": "Quảng cáo", "advice": "Lời khuyên", "advise": "Khuyên", "advocate": "Ủng hộ", "aesthetic": "Thẩm mỹ", "affair": "Công việc",
        "affect": "Ảnh hưởng", "affection": "Sự yêu mến", "afford": "Có đủ khả năng", "affordable": "Giá cả phải chăng", "afraid": "Sợ",
        "after": "Sau", "aftermath": "Hậu quả", "afternoon": "Buổi chiều", "afterwards": "Sau đó", "again": "Lại", "against": "Chống lại",
        "age": "Tuổi", "aged": "Lớn tuổi", "agency": "Đại lý", "agenda": "Chương trình nghị sự", "agent": "Đại lý", "aggravate": "Làm trầm trọng thêm",
        "aggression": "Sự xâm lược", "aggressive": "Hung hăng", "ago": "Trước đây", "agree": "Đồng ý", "agreement": "Thỏa thuận",
        "agricultural": "Nông nghiệp", "agriculture": "Nông nghiệp", "ahead": "Phía trước", "aid": "Viện trợ", "aide": "Trợ lý", "aids": "HIV/AIDS",
        "aim": "Mục tiêu", "air": "Không khí", "aircraft": "Máy bay", "airline": "Hãng hàng không", "airport": "Sân bay", "alarm": "Báo động",
        "albeit": "Mặc dù", "album": "Album", "alcohol": "Cồn, rượu", "alcoholic": "Rượu bia", "alert": "Cảnh báo", "alien": "Người ngoài hành tinh",
        "align": "Căn chỉnh", "alignment": "Sự căn chỉnh", "alike": "Giống nhau", "alive": "Sống", "all": "Tất cả", "allegation": "Cáo buộc",
        "allege": "Cáo buộc", "allegedly": "Được cho là", "alliance": "Liên minh", "allocate": "Phân bổ", "allocation": "Sự phân bổ",
        "allow": "Cho phép", "allowance": "Tiền trợ cấp", "ally": "Đồng minh", "almost": "Hầu như", "alone": "Một mình", "along": "Dọc theo",
        "alongside": "Bên cạnh", "aloud": "Lớn tiếng", "alphabet": "Bảng chữ cái", "already": "Đã", "also": "Cũng", "alter": "Thay đổi",
        "alternative": "Thay thế", "alternatively": "Thay vào đó", "although": "Mặc dù", "altitude": "Độ cao", "altogether": "Hoàn toàn",
        "aluminum": "Nhôm", "always": "Luôn luôn", "amateur": "Nghiệp dư", "amazed": "Ngạc nhiên", "amazing": "Tuyệt vời", "ambassador": "Đại sứ",
        "ambiguity": "Sự mơ hồ", "ambiguous": "Mơ hồ", "ambition": "Tham vọng", "ambitious": "Tham vọng", "ambulance": "Xe cứu thương",
        "amend": "Sửa đổi", "amendment": "Sự sửa đổi", "amid": "Giữa", "among": "Trong số", "amount": "Số lượng", "amusing": "Vui nhộn",
        "analogy": "Sự tương tự", "analysis": "Phân tích", "analyst": "Nhà phân tích", "analyze": "Phân tích", "ancestor": "Tổ tiên",
        "anchor": "Mỏ neo", "ancient": "Cổ đại", "and": "Và", "anecdote": "Giai thoại", "anger": "Sự tức giận", "angle": "Góc", "angry": "Tức giận",
        "animal": "Động vật", "animation": "Hoạt hình", "ankle": "Mắt cá chân", "anniversary": "Kỷ niệm", "announce": "Thông báo",
        "announcement": "Thông báo", "annoy": "Làm phiền", "annoyed": "Bị làm phiền", "annoying": "Gây phiền nhiễu", "annual": "Hàng năm",
        "annually": "Hàng năm", "anonymous": "Ẩn danh", "another": "Khác", "answer": "Trả lời", "ant": "Con kiến", "anticipate": "Dự đoán",
        "anxiety": "Sự lo lắng", "anxious": "Lo lắng", "any": "Bất kỳ", "anybody": "Bất cứ ai", "anyhow": "Dù sao đi nữa", "anymore": "Nữa",
        "anyone": "Bất cứ ai", "anything": "Bất cứ điều gì", "anyway": "Dù sao đi nữa", "anywhere": "Bất cứ nơi nào", "apart": "Tách rời",
        "apartment": "Căn hộ", "apologize": "Xin lỗi", "apology": "Lời xin lỗi", "app": "Ứng dụng", "apparatus": "Bộ máy", "apparent": "Rõ ràng",
        "apparently": "Hình như", "appeal": "Kháng cáo, hấp dẫn", "appealing": "Hấp dẫn", "appear": "Xuất hiện", "appearance": "Ngoại hình",
        "appetite": "Sự thèm ăn", "apple": "Quả táo", "applicable": "Có thể áp dụng", "applicant": "Người nộp đơn", "application": "Ứng dụng",
        "apply": "Áp dụng", "appoint": "Bổ nhiệm", "appointment": "Cuộc hẹn", "appreciate": "Đánh giá cao", "appreciation": "Sự cảm kích",
        "approach": "Tiếp cận", "appropriate": "Thích hợp", "appropriately": "Một cách thích hợp", "approval": "Sự chấp thuận", "approve": "Phê duyệt",
        "approximate": "Xấp xỉ", "approximately": "Khoảng", "april": "Tháng Tư", "arbitrary": "Tùy tiện", "architect": "Kiến trúc sư",
        "architecture": "Kiến trúc", "archive": "Kho lưu trữ", "area": "Khu vực", "arena": "Đấu trường", "arguably": "Có thể cho rằng",
        "argue": "Trình bày, tranh luận", "argument": "Lập luận", "arise": "Nảy sinh", "arm": "Cánh tay", "armed": "Vũ trang", "arms": "Vũ khí",
        "army": "Quân đội", "around": "Xung quanh", "arrange": "Sắp xếp", "arrangement": "Sự sắp xếp", "array": "Mảng", "arrest": "Bắt giữ",
        "arrival": "Sự đến", "arrive": "Đến", "arrow": "Mũi tên", "art": "Nghệ thuật", "article": "Bài báo", "articulate": "Khéo léo",
        "artificial": "Nhân tạo", "artist": "Nghệ sĩ", "artistic": "Nghệ thuật", "as": "Như là", "ash": "Tro", "ashamed": "Xấu hổ", "aside": "Sang một bên",
        "ask": "Hỏi", "asleep": "Ngủ", "aspect": "Khía cạnh", "aspiration": "Khát vọng", "aspire": "Khát khao", "assassination": "Vụ ám sát",
        "assault": "Cuộc tấn công", "assemble": "Lắp ráp", "assembly": "Hội đồng", "assert": "Khẳng định", "assertion": "Sự khẳng định",
        "assess": "Đánh giá", "assessment": "Đánh giá", "asset": "Tài sản", "assign": "Phân công", "assignment": "Bài tập", "assist": "Hỗ trợ",
        "assistance": "Sự hỗ trợ", "assistant": "Trợ lý", "associate": "Liên kết", "associated": "Liên quan", "association": "Hiệp hội",
        "assume": "Giả định", "assumption": "Giả định", "assurance": "Sự đảm bảo", "assure": "Đảm bảo", "asteroid": "Tiểu hành tinh",
        "astonishing": "Đáng kinh ngạc", "asylum": "Tị nạn", "at": "Tại", "athlete": "Vận động viên", "atmosphere": "Bầu không khí",
        "atrocity": "Sự tàn bạo", "attach": "Đính kèm", "attachment": "Tệp đính kèm", "attack": "Tấn công", "attain": "Đạt được", "attempt": "Cố gắng",
        "attend": "Tham dự", "attendance": "Sự tham dự", "attention": "Sự chú ý", "attitude": "Thái độ", "attorney": "Luật sư", "attract": "Thu hút",
        "attraction": "Điểm thu hút", "attractive": "Hấp dẫn", "attribute": "Thuộc tính", "auction": "Đấu giá", "audience": "Khán giả",
        "audio": "Âm thanh", "audit": "Kiểm toán", "august": "Tháng Tám", "aunt": "Cô, dì", "authentic": "Đích thực", "author": "Tác giả",
        "authority": "Chính quyền", "authorize": "Ủy quyền", "auto": "Tự động", "automatic": "Tự động", "automatically": "Tự động",
        "autumn": "Mùa thu", "availability": "Tính khả dụng", "available": "Có sẵn", "average": "Trung bình", "avoid": "Tránh", "await": "Chờ đợi",
        "awake": "Tỉnh táo", "award": "Giải thưởng", "aware": "Nhận thức", "awareness": "Nhận thức", "away": "Xa", "awful": "Kinh khủng",
        "awkward": "Hậu đậu, lúng túng", "baby": "Em bé", "back": "Quay lại, lưng", "backdrop": "Cối cảnh", "background": "Lý lịch, nền",
        "backing": "Sự hỗ trợ", "backup": "Sao lưu", "backward": "Lùi lại", "bacteria": "Vi khuẩn", "bad": "Tồi tệ", "badge": "Huy hiệu",
        "badly": "Tồi tệ", "bag": "Túi", "bail": "Tiền bảo lãnh", "bake": "Nướng", "balance": "Số dư, cân bằng", "balanced": "Cân bằng",
        "ball": "Quả bóng", "ballet": "Ba lê", "balloon": "Quả bóng bay", "ballot": "Phiếu bầu", "ban": "Cấm", "banana": "Quả chuối",
        "band": "Ban nhạc", "bank": "Ngân hàng", "banner": "Biểu ngữ", "bar": "Quầy bar, thanh", "bare": "Trần trụi", "barely": "Vừa đủ",
        "bargain": "Mặc cả", "barrel": "Thùng rượu", "barrier": "Rào chắn", "base": "Căn cứ", "baseball": "Bóng chày", "based": "Dựa trên",
        "baseline": "Đường cơ sở", "basic": "Cơ bản", "basically": "Về cơ bản", "basis": "Cơ sở", "basket": "Cái giỏ", "basketball": "Bóng rổ",
        "bath": "Tắm", "bathroom": "Phòng tắm", "battery": "Pin", "battle": "Trận chiến", "battlefield": "Chiến trường", "bay": "Vịnh",
        "be": "Thì, là, ở", "beach": "Bãi biển", "beam": "Chùm tia", "bean": "Hạt đậu", "bear": "Con gấu, chịu đựng", "beast": "Quái thú",
        "beat": "Đánh bại", "beautiful": "Đẹp", "beauty": "Vẻ đẹp", "because": "Bởi vì", "become": "Trở nên", "bed": "Giường", "bedroom": "Phòng ngủ",
        "bee": "Con ong", "beef": "Thịt bò", "beer": "Bia", "before": "Trước", "beg": "Cầu xin", "begin": "Bắt đầu", "beginning": "Sự bắt đầu",
        "behalf": "Thay mặt", "behave": "Hành xử", "behavior": "Hành vi", "behind": "Phía sau", "being": "Sự tồn tại", "belief": "Niềm tin",
        "believe": "Tin tưởng", "bell": "Cái chuông", "belong": "Thuộc về", "beloved": "Được yêu mến", "below": "Phía dưới", "belt": "Thắt lưng",
        "bench": "Ghế dự bị", "benchmark": "Điểm chuẩn", "bend": "Bẻ cong", "beneath": "Bên dưới", "beneficial": "Có lợi", "beneficiary": "Người thụ hưởng",
        "benefit": "Lợi ích", "bent": "Uốn cong", "beside": "Bên cạnh", "besides": "Ngoài ra", "best": "Tốt nhất", "best-seller": "Sách bán chạy",
        "bet": "Đặt cược", "betray": "Phản bội", "better": "Tốt hơn", "between": "Giữa", "beyond": "Vượt ra ngoài", "bias": "Thành kiến",
        "bicycle": "Xe đạp", "bid": "Đấu thầu", "big": "Lớn", "bike": "Xe đạp", "bill": "Hóa đơn", "billion": "Tỷ", "bin": "Thùng rác",
        "bind": "Liên kết", "biography": "Tiểu sử", "biological": "Sinh học", "biology": "Sinh học", "bird": "Con chim", "birth": "Sự ra đời",
        "birthday": "Sinh nhật", "biscuit": "Bánh quy", "bishop": "Giám mục", "bit": "Một ít", "bite": "Cắn", "bitter": "Đắng", "bizarre": "Kỳ lạ",
        "black": "Màu đen", "blade": "Lưỡi dao", "blame": "Đổ lỗi", "blank": "Trống", "blast": "Vụ nổ", "blaze": "Ngọn lửa", "bleed": "Chảy máu",
        "blend": "Hỗn hợp", "bless": "Chúc phúc", "blessing": "Lời chúc phúc", "blind": "Mù", "block": "Khối", "blog": "Blog", "blonde": "Vàng hoe",
        "blood": "Máu", "blow": "Thổi", "blue": "Màu xanh da trời", "board": "Hội đồng, bảng", "boast": "Khoe khoang", "boat": "Thuyền",
        "body": "Cơ thể", "boil": "Luộc, sôi", "bold": "Táo bạo, in đậm", "bomb": "Bom", "bombing": "Vụ ném bom", "bond": "Sự liên kết",
        "bone": "Xương", "bonus": "Tiền thưởng", "book": "Quyển sách", "booking": "Đặt chỗ", "boom": "Sự bùng nổ", "boost": "Tăng cường",
        "boot": "Khởi động, ủng", "border": "Biên giới", "bored": "Chán", "boring": "Chán", "born": "Sinh ra", "borrow": "Vay mượn", "boss": "Ông chủ",
        "both": "Cả hai", "bother": "Làm phiền", "bottle": "Cái chai", "bottom": "Đáy", "bounce": "Nảy lên", "bound": "Ràng buộc",
        "boundary": "Ranh giới", "bow": "Cúi chào, cây cung", "bowl": "Cái bát", "box": "Cái hộp", "boy": "Cậu bé", "boyfriend": "Bạn trai",
        "brace": "Nẹp", "brain": "Não", "branch": "Chi nhánh", "brand": "Thương hiệu", "brave": "Dũng cảm", "breach": "Vi phạm", "bread": "Bánh mì",
        "break": "Nghỉ ngơi, vỡ", "breakdown": "Sự cố, hỏng hóc", "breakfast": "Bữa sáng", "breakthrough": "Đột phá", "breast": "Ngực",
        "breath": "Hơi thở", "breathe": "Thở", "breathing": "Sự thở", "breed": "Giống loài", "brick": "Viên gạch", "bridge": "Cây cầu",
        "brief": "Ngắn gọn", "briefly": "Ngắn gọn", "bright": "Sáng sủa", "brilliant": "Tuyệt vời", "bring": "Mang lại", "broad": "Rộng",
        "broadcast": "Phát sóng", "broadcaster": "Phát thanh viên", "broadly": "Nói chung", "broken": "Bị hỏng", "bronze": "Đồng", "brother": "Anh em",
        "brown": "Màu nâu", "browse": "Duyệt", "browser": "Trình duyệt", "brush": "Bàn chải", "brutal": "Tàn bạo", "bubble": "Bong bóng",
        "buck": "Đồng đô la", "bucket": "Cái xô", "buddy": "Người bạn", "budget": "Ngân sách", "buffer": "Bộ nhớ đệm", "bug": "Lỗi", "build": "Xây dựng",
        "builder": "Người thây", "building": "Tòa nhà", "bulb": "Bóng đèn", "bulk": "Số lượng lớn", "bullet": "Viên đạn", "bunch": "Chùm",
        "burden": "Gánh nặng", "bureaucracy": "Quan liêu", "burial": "An táng", "burn": "Đốt cháy", "burst": "Bùng nổ", "bury": "Chôn",
        "bus": "Xe buýt", "bush": "Bụi cây", "business": "Kinh doanh", "businessman": "Nam doanh nhân", "busy": "Bận", "but": "Nhưng",
        "butter": "Bơ", "button": "Nút", "buy": "Mua", "buyer": "Người mua", "by": "Bởi", "cab": "Xe taxi", "cabin": "Cabin", "cabinet": "Tủ, nội các",
        "cable": "Cáp", "cafe": "Quán cà phê", "cake": "Bánh", "calculate": "Tính toán", "calculation": "Phép tính", "calendar": "Lịch",
        "call": "Gọi", "calm": "Bình tĩnh", "camera": "Máy ảnh", "camp": "Trại", "campaign": "Chiến dịch", "camping": "Cắm trại", "campus": "Khu viên",
        "can": "Có thể", "canal": "Kênh đào", "cancel": "Hủy bỏ", "cancer": "Ung thư", "candidate": "Ứng cử viên", "candle": "Cây nến",
        "candy": "Kẹo", "cannon": "Đại bác", "canvas": "Vải bạt", "capability": "Khả năng", "capable": "Có khả năng", "capacity": "Năng lực",
        "cape": "Áo choàng, mũi đất", "capital": "Thủ đô, vốn", "captain": "Thuyền trưởng", "caption": "Phụ đề", "capture": "Bắt giữ",
        "car": "Xe hơi", "carbon": "Cacbon", "card": "Thẻ", "care": "Chăm sóc", "career": "Sự nghiệp", "careful": "Cẩn thận", "carefully": "Cẩn thận",
        "careless": "Bất cẩn", "cargo": "Hàng hóa", "carpet": "Thảm", "carriage": "Toa xe", "carrier": "Người vận chuyển", "carrot": "Cà rốt",
        "carry": "Mang", "cart": "Xe đẩy", "cartoon": "Hoạt hình", "carve": "Chạm khắc", "case": "Trường hợp", "cash": "Tiền mặt", "casino": "Sòng bạc",
        "cast": "Dàn diễn viên", "castle": "Lâu đài", "casual": "Thông thường", "casualty": "Thương vong", "cat": "Con mèo", "catalog": "Danh mục",
        "catch": "Bắt lấy", "category": "Loại", "cater": "Phục vụ", "cattle": "Gia súc", "cause": "Nguyên nhân", "caution": "Thận trọng",
        "cautious": "Thận trọng", "cave": "Hang động", "cease": "Ngừng", "ceiling": "Trần nhà", "celebrate": "Kỷ niệm", "celebration": "Lễ kỷ niệm",
        "celebrity": "Người nổi tiếng", "cell": "Tế bào", "cemetery": "Nghĩa trang", "census": "Điều tra dân số", "cent": "Xu", "center": "Trung tâm",
        "central": "Trung tâm", "century": "Thế kỷ", "ceremony": "Nghi lễ", "certain": "Chắc chắn", "certainly": "Chắc chắn", "certainty": "Sự chắc chắn",
        "certificate": "Chứng chỉ", "chain": "Chuỗi", "chair": "Cái ghế", "chairman": "Chủ tịch", "challenge": "Thử thách", "challenging": "Đầy thử thách",
        "chamber": "Buồng", "champion": "Nhà vô địch", "championship": "Giải vô địch", "chance": "Cơ hội", "change": "Thay đổi", "channel": "Kênh",
        "chaos": "Sự hỗn loạn", "chapter": "Chương", "character": "Nhân vật", "characteristic": "Đặc trưng", "characterize": "Đặc trưng cho",
        "charge": "Sạc, tính phí", "charity": "Hội từ thiện", "charm": "Sức hấp dẫn", "charming": "Quyến rũ", "chart": "Biểu đồ", "charter": "Hiến chương",
        "chase": "Rượt đuổi", "chat": "Trò chuyện", "cheap": "Rẻ", "cheat": "Gian lận", "check": "Kiểm tra", "cheek": "Má", "cheer": "Vui vẻ",
        "cheerful": "Vui vẻ", "cheese": "Phô mai", "chef": "Đầu bếp", "chemical": "Hóa chất", "chemistry": "Hóa học", "chest": "Ngực",
        "chicken": "Con gà", "chief": "Người đứng đầu", "child": "Đứa trẻ", "childhood": "Tuổi thơ", "chip": "Chip, khoai tây chiên",
        "chocolate": "Sô cô la", "choice": "Sự lựa chọn", "choir": "Dàn hợp xướng", "choose": "Chọn", "chop": "Chặt, băm", "chronic": "Mãn tính",
        "chronicle": "Biên niên sử", "chunk": "Khúc, tảng", "church": "Nhà thờ", "cigarette": "Thuốc lá", "cinema": "Rạp chiếu phim",
        "circle": "Vòng tròn", "circuit": "Mạch điện", "circulate": "Lưu thông", "circulation": "Sự lưu thông", "circumstance": "Hoàn cảnh",
        "cite": "Trích dẫn", "citizen": "Công dân", "citizenship": "Quyền công dân", "city": "Thành phố", "civic": "Thuộc công dân", "civil": "Dân sự",
        "civilian": "Thường dân", "civilization": "Nền văn minh", "claim": "Tuyên bố", "clarity": "Sự rõ ràng", "clash": "Sự xung đột",
        "class": "Lớp học", "classic": "Cổ điển", "classical": "Cổ điển", "classification": "Phân loại", "classify": "Phân loại",
        "classroom": "Lớp học", "clause": "Điều khoản", "clay": "Đất sét", "clean": "Sạch", "cleaning": "Dọn dẹp", "clear": "Rõ ràng",
        "clearly": "Một cách rõ ràng", "clerk": "Thư ký", "clever": "Thông minh", "click": "Nhấp chuột", "client": "Khách hàng", "cliff": "Vách đá",
        "climate": "Khí hậu", "climb": "Leo", "cling": "Bám lấy", "clinic": "Phòng khám", "clinical": "Lâm sàng", "clip": "Clip", "clock": "Đồng hồ",
        "close": "Đóng, gần", "closed": "Đã đóng", "closely": "Chặt chẽ", "closure": "Sự đóng cửa", "cloth": "Vải", "clothes": "Quần áo",
        "clothing": "Quần áo", "cloud": "Mây", "club": "Câu lạc bộ", "clue": "Manh mối", "cluster": "Cụm", "coach": "Huấn luyện viên",
        "coal": "Than đá", "coalition": "Liên minh", "coast": "Bờ biển", "coastal": "Ven biển", "coat": "Áo khoác", "cocktail": "Cocktail",
        "code": "Mật mã, code", "coffee": "Cà phê", "cognitive": "Nhận thức", "coin": "Đồng xu", "coincide": "Trùng hợp", "coincidence": "Sự trùng hợp",
        "cold": "Lạnh", "collaborate": "Hợp tác", "collaboration": "Sự hợp tác", "collapse": "Sụp đổ", "colleague": "Đồng nghiệp",
        "collect": "Thu thập", "collection": "Bộ sưu tập", "collective": "Tập thể", "collector": "Người sưu tầm", "college": "Cao đẳng",
        "collision": "Vụ va chạm", "colonial": "Thuộc địa", "colony": "Thuộc địa", "color": "Màu sắc", "colored": "Có màu", "colorful": "Đầy màu sắc",
        "column": "Cột", "columnist": "Người viết chuyên mục", "combat": "Chiến đấu", "combination": "Sự kết hợp", "combine": "Kết hợp",
        "combined": "Kết hợp", "come": "Đến", "comedy": "Hài kịch", "comfort": "Sự thoải mái", "comfortable": "Thoải mái", "comic": "Truyện tranh",
        "command": "Ra lệnh", "commander": "Chỉ huy", "commence": "Bắt đầu", "comment": "Bình luận", "commentary": "Lời bình luận",
        "commentator": "Bình luận viên", "commerce": "Thương mại", "commercial": "Thương mại", "commission": "Uỷ ban, tiền hoa hồng",
        "commissioner": "Ủy viên", "commit": "Cam kết", "commitment": "Sự cam kết", "committee": "Ủy ban", "commodity": "Hàng hóa",
        "common": "Phổ biến", "commonly": "Thường xuyên", "communicate": "Giao tiếp", "communication": "Giao tiếp", "communion": "Sự hiệp thông",
        "communist": "Cộng sản", "community": "Cộng đồng", "companion": "Người bạn đồng hành", "company": "Công ty", "comparable": "Có thể so sánh",
        "comparative": "So sánh", "compare": "So sánh", "comparison": "Sự so sánh", "compassion": "Lòng trắc ẩn", "compel": "Bắt buộc",
        "compelling": "Hấp dẫn", "compensate": "Bồi thường", "compensation": "Sự bồi thường", "compete": "Cạnh tranh", "competence": "Năng lực",
        "competent": "Có năng lực", "competition": "Cuộc cạnh tranh", "competitive": "Cạnh tranh", "competitor": "Đối thủ cạnh tranh",
        "compile": "Biên soạn", "complain": "Khiếu nại", "complaint": "Lời khiếu nại", "complement": "Bổ sung", "complete": "Hoàn thành",
        "completely": "Hoàn toàn", "completion": "Sự hoàn thành", "complex": "Phức tạp", "complexity": "Sự phức tạp", "compliance": "Sự tuân thủ",
        "complicated": "Phức tạp", "comply": "Tuân thủ", "component": "Thành phần", "compose": "Sáng tác", "composer": "Nhà soạn nhạc",
        "composition": "Sách sáng tác", "compound": "Hợp chất", "comprehensive": "Toàn diện", "comprise": "Bao gồm", "compromise": "Thỏa hiệp",
        "compulsory": "Bắt buộc", "compute": "Tính toán", "computer": "Máy tính", "conceal": "Che giấu", "concede": "Thừa nhận",
        "conceivable": "Có thể tưởng tượng", "conceive": "Hình thành", "concentrate": "Tập trung", "concentration": "Sự tập trung",
        "concept": "Khái niệm", "conception": "Quan niệm", "concern": "Mối quan tâm", "concerned": "Lo ngại", "concert": "Buổi hòa nhạc",
        "concession": "Sự nhượng bộ", "conclude": "Kết luận", "conclusion": "Kết luận", "concrete": "Bê tông, cụ thể", "condemn": "Lên án",
        "condition": "Điều kiện", "conduct": "Hành vi, tiến hành", "confer": "Trao tặng", "conference": "Hội nghị", "confess": "Thú nhận",
        "confession": "Sự thú tội", "confidence": "Sự tự tin", "confident": "Tự tin", "configuration": "Cấu hình", "confine": "Giam cầm",
        "confirm": "Xác nhận", "confirmation": "Sự xác nhận", "conflict": "Xung đột", "conform": "Tuân thủ", "confront": "Đối mặt",
        "confrontation": "Sự đối đầu", "confuse": "Làm rối trí", "confused": "Bị rối trí", "confusing": "Gây nhầm lẫn", "confusion": "Sự nhầm lẫn",
        "congratulate": "Chúc mừng", "congress": "Quốc hội", "congressional": "Thuộc quốc hội", "conjunction": "Sự kết hợp", "connect": "Kết nối",
        "connected": "Kết nối", "connection": "Kết nối", "conquer": "Chinh phục", "conscience": "Lương tâm", "conscious": "Tỉnh táo",
        "consciousness": "Ý thức", "consecutive": "Liên tiếp", "consensus": "Sự đồng thuận", "consent": "Sự đồng ý", "consequence": "Hậu quả",
        "consequently": "Kết quả là", "conservation": "Sự bảo tồn", "conservative": "Bảo thủ", "conserve": "Bảo tồn", "consider": "Cân nhắc",
        "considerable": "Đáng kể", "considerably": "Đáng kể", "consideration": "Sự cân nhắc", "consist": "Bao gồm", "consistency": "Tính nhất quán",
        "consistent": "Nhất quán", "consistently": "Nhất quán", "consolidate": "Củng cố", "conspiracy": "Âm mưu", "constable": "Cảnh sát",
        "constant": "Không thay đổi", "constantly": "Liên tục", "constitute": "Cấu thành", "constitution": "Hiến pháp", "constitutional": "Hiến pháp",
        "constraint": "Ràng buộc", "construct": "Xây dựng", "construction": "Xây dựng", "consult": "Tham khảo", "consultant": "Cố vấn",
        "consultation": "Sự tham vấn", "consume": "Tiêu dùng", "consumer": "Người tiêu dùng", "consumption": "Sự tiêu thụ", "contact": "Liên hệ",
        "contain": "Chứa đựng", "container": "Thùng chứa", "contaminate": "Làm ô nhiễm", "contemporary": "Đương đại", "contempt": "Sự khinh miệt",
        "contend": "Đấu tranh", "content": "Nội dung", "contention": "Trận cãi", "contest": "Cuộc thi", "context": "Ngữ cảnh", "continent": "Lục địa",
        "continual": "Liên miên", "continue": "Tiếp tục", "continuous": "Liên tục", "continuously": "Liên tục", "contract": "Hợp đồng",
        "contractor": "Nhà thầu", "contradict": "Mâu thuẫn", "contradiction": "Mâu thuẫn", "contrary": "Ngược lại", "contrast": "Tương phản",
        "contribute": "Đóng góp", "contribution": "Đóng góp", "contributor": "Người đóng góp", "control": "Kiểm soát", "controversial": "Gây tranh cãi",
        "controversy": "Sự tranh cãi", "convenience": "Tiện lợi", "convenient": "Tiện lợi", "convention": "Hội nghị, quy ước",
        "conventional": "Thông thường", "conversation": "Cuộc hội thoại", "conversion": "Sự chuyển đổi", "convert": "Chuyển đổi", "convey": "Truyền đạt",
        "convict": "Kết án", "conviction": "Sự kết án", "convince": "Thuyết phục", "convinced": "Thuyết phục", "convincing": "Thuyết phục",
        "cook": "Nấu ăn", "cooker": "Nồi cơm điện", "cooking": "Nấu ăn", "cool": "Mát, ngầu", "cooperate": "Hợp tác", "cooperation": "Sự hợp tác",
        "cooperative": "Hợp tác", "coordinate": "Phối hợp", "coordination": "Sự phối hợp", "coordinator": "Điều phối viên", "cop": "Cảnh sát",
        "cope": "Đối phó", "copper": "Đồng", "copy": "Bản sao", "copyright": "Bản quyền", "core": "Cốt lõi", "corn": "Ngô", "corner": "Góc",
        "corporate": "Doanh nghiệp", "corporation": "Tập đoàn", "correct": "Chính xác", "correction": "Sửa chữa", "correctly": "Chính xác",
        "correlate": "Tương quan", "correlation": "Sự tương quan", "correspond": "Tương ứng", "correspondence": "Thư tín",
        "correspondent": "Phóng viên", "corresponding": "Tương ứng", "corridor": "Hành lang", "corrupt": "Tham nhũng", "corruption": "Sự tham nhũng",
        "cost": "Chi phí", "costly": "Đắt tiền", "costume": "Trang phục", "cottage": "Nhà gỗ", "cotton": "Bông", "couch": "Ghế sofa",
        "could": "Có thể", "council": "Hội đồng", "counsel": "Tư vấn", "counseling": "Tư vấn", "counselor": "Cố vấn", "count": "Đếm",
        "counter": "Quầy", "counterpart": "Đối tác", "countless": "Vô số", "country": "Quốc gia", "countryside": "Nông thôn", "county": "Quận",
        "coup": "Cuộc đảo chính", "couple": "Cặp đôi", "courage": "Dũng cảm", "course": "Khóa học", "court": "Tòa án", "courtesy": "Lịch sự",
        "cousin": "Anh chị em họ", "cover": "Bao phủ", "coverage": "Độ bao phủ", "covered": "Bao phủ", "cow": "Con bò", "crack": "Vết nứt",
        "craft": "Nghề thủ công", "crash": "Tai nạn", "crawl": "Bò", "crazy": "Điên", "create": "Tạo ra", "creation": "Sự sáng tạo",
        "creative": "Sáng tạo", "creativity": "Tính sáng tạo", "creator": "Người sáng tạo", "creature": "Sinh vật", "credibility": "Uy tín",
        "credible": "Đáng tin cậy", "credit": "Tín dụng", "creep": "Leo lẻo", "crew": "Phi hành đoàn", "crime": "Tội ác", "criminal": "Tội phạm",
        "crisis": "Khủng hoảng", "criterion": "Tiêu chí", "critic": "Nhà phê bình", "critical": "Chỉ trích, quan trọng", "critically": "Chỉ trích",
        "criticism": "Lời chỉ trích", "criticize": "Chỉ trích", "critique": "Lời phê bình", "crop": "Vụ mùa", "cross": "Băng qua",
        "crowd": "Đám đông", "crowded": "Đông đúc", "crown": "Vương miện", "crucial": "Quan trọng", "crude": "Thô", "cruel": "Độc ác",
        "cruise": "Du thuyền", "crush": "Đè nát", "cry": "Khóc", "crystal": "Pha lê", "cue": "Gợi ý", "cult": "Tôn giáo", "cultivate": "Nuôi dưỡng",
        "cultural": "Văn hóa", "culture": "Văn hoá", "cup": "Cái cốc", "cupboard": "Tủ đựng chén", "curb": "Kiềm chế", "cure": "Chữa khỏi",
        "curiosity": "Sự tò mò", "curious": "Tò mò", "currency": "Tiền tệ", "current": "Hiện tại", "currently": "Hiện tại", "curriculum": "Chương trình học",
        "curtain": "Rèm cửa", "curve": "Đường cong", "curved": "Cong", "custody": "Giam giữ", "custom": "Phong tục", "customer": "Khách hàng",
        "cut": "Cắt", "cute": "Dễ thương", "cutting": "Cắt", "cyber": "Mạng", "cycle": "Chu kỳ", "cycling": "Đi xe đạp", "cynical": "Hoài nghi",
        "daily": "Hàng ngày", "dairy": "Sản phẩm bơ sữa", "damage": "Thiệt hại", "damaged": "Bị hư hỏng", "damaging": "Gây hại",
        "dance": "Nhảy múa", "dancer": "Diễn viên múa", "dancing": "Sự nhảy múa", "danger": "Nguy hiểm", "dangerous": "Nguy hiểm",
        "dare": "Dám", "dark": "Tối", "darkness": "Bóng tối", "data": "Dữ liệu", "database": "Cơ sở dữ liệu", "date": "Ngày, hẹn hò",
        "daughter": "Con gái", "dawn": "Bình minh", "day": "Ngày", "dead": "Chết", "deadline": "Hạn chót", "deadly": "Chết người",
        "deaf": "Điếc", "deal": "Thỏa thuận, giải quyết", "dealer": "Người buôn bán", "dear": "Thân mến, đắt", "death": "Cái chết",
        "debate": "Tranh luận", "debris": "Mảnh vụn", "debt": "Khoản nợ", "debut": "Sự ra mắt", "decade": "Thập kỷ",
        "december": "Tháng Mười Hai", "decent": "Tử tế", "decide": "Quyết định", "decision": "Quyết định", "decision-making": "Ra quyết định",
        "deck": "Boong tàu", "declare": "Tuyên bố", "decline": "Từ chối, giảm", "decorate": "Trang trí", "decoration": "Sự trang trí",
        "decrease": "Giảm bớt", "dedicated": "Tận tâm", "dedication": "Sự cống hiến", "deed": "Hành động, chứng thư", "deep": "Sâu",
        "deeply": "Sâu sắc", "default": "Mặc định", "defeat": "Đánh bại", "defect": "Thiếu sót, lỗi", "defence": "Phòng thủ",
        "defend": "Bảo vệ", "defender": "Người bảo vệ", "defensive": "Phòng thủ", "deficiency": "Sự thiếu hụt", "deficit": "Thâm hụt",
        "define": "Định nghĩa", "definite": "Xác định", "definitely": "Chắc chắn", "definition": "Định nghĩa", "defy": "Thách thức",
        "degree": "Độ, bằng cấp", "delay": "Trì hoãn", "delegate": "Đại biểu", "delegation": "Đoàn đại biểu", "delete": "Xóa",
        "deliberate": "Thận trọng, cố ý", "deliberately": "Cố ý", "delicate": "Mong manh, tinh tế", "delicious": "Ngon", "delight": "Vui mừng",
        "delighted": "Vui mừng", "deliver": "Giao hàng", "delivery": "Giao hàng", "demand": "Nhu cầu, yêu cầu", "democracy": "Dân chủ",
        "democratic": "Dân chủ", "democrat": "Người theo đảng dân chủ", "demonstrate": "Chứng minh", "demonstration": "Sự chứng minh",
        "denial": "Sự phủ nhận", "denounce": "Tố cáo", "dense": "Dày đặc", "density": "Mật độ", "dentist": "Nha sĩ", "deny": "Phủ nhận",
        "depart": "Khởi hành", "department": "Phòng ban", "departure": "Sự khởi hành", "depend": "Phụ thuộc", "dependence": "Sự phụ thuộc",
        "dependent": "Phụ thuộc", "depict": "Mô tả", "deployment": "Sự triển khai", "deposit": "Tiền gửi, đặt cọc", "depression": "Trầm cảm, suy thoái",
        "deprive": "Tước đoạt", "depth": "Chiều sâu", "deputy": "Phó, đại biểu", "derive": "Bắt nguồn từ", "descend": "Đi xuống",
        "descent": "Sự đi xuống", "describe": "Mô tả", "description": "Sự mô tả", "desert": "Sa mạc", "deserve": "Xứng đáng",
        "design": "Thiệt kế", "designer": "Nhà thiết kế", "desirable": "Đáng khao khát", "desire": "Khao khát", "desk": "Bàn làm việc",
        "desktop": "Máy tính để bàn", "desperate": "Tuyệt vọng", "desperately": "Tuyệt vọng", "despite": "Mặc dù", "destination": "Điểm đến",
        "destroy": "Phá hủy", "destruction": "Sự phá hủy", "destructive": "Phá hoại", "detach": "Tháo rời", "detail": "Chi tiết",
        "detailed": "Chi tiết", "detain": "Giam giữ", "detect": "Phát hiện", "detection": "Sự phát hiện", "detective": "Thám tử",
        "detention": "Sự giam giữ", "deteriorate": "Xấu đi", "determination": "Sự quyết tâm", "determine": "Xác định", "determined": "Quyết tâm",
        "devastate": "Tàn phá", "develop": "Phát triển", "developer": "Nhà phát triên", "developing": "Đang phát triển", "development": "Sự phát triển",
        "developmental": "Thuộc phát triển", "device": "Thiết bị", "devil": "Ác quỷ", "devise": "Phát minh", "devote": "Cống hiến",
        "devotion": "Sự tận tâm", "diabetes": "Bệnh tiểu đường", "diagnosis": "Chẩn đoán", "diagnose": "Chẩn đoán", "diagram": "Biểu đồ",
        "dialogue": "Đối thoại", "diamond": "Kim cương", "diary": "Nhật ký", "dictate": "Ra lệnh, đọc cho viết", "dictator": "Kẻ độc tài",
        "dictionary": "Từ điển", "die": "Chết", "diet": "Chế độ ăn uống", "differ": "Khác biệt", "difference": "Sự khác biệt",
        "different": "Khác", "differentiate": "Phân biệt", "differently": "Khác nhau", "difficult": "Khó khăn", "difficulty": "Sự khó khăn",
        "dig": "Đào", "digital": "Kỹ thuật số", "dignity": "Phẩm giá", "dilemma": "Tình thế tiến thoái lưỡng nan", "dimension": "Kích thước, khía cạnh",
        "diminish": "Giảm bớt", "dinner": "Bữa tối", "dip": "Nhúng", "diplomat": "Nhà ngoại giao", "diplomatic": "Ngoại giao",
        "direct": "Trực tiếp", "direction": "Hướng", "directive": "Chỉ thị", "directly": "Trực tiếp", "director": "Giám đốc",
        "directory": "Danh bạ", "dirt": "Bụi bẩn", "dirty": "Bẩn", "disability": "Khuyết tật", "disabled": "Tàn tật",
        "disadvantage": "Bất lợi", "disagree": "Không đồng ý", "disagreement": "Sự không đồng ý", "disappear": "Biến mất",
        "disappoint": "Làm thất vọng", "disappointed": "Thất vọng", "disappointing": "Đáng thất vọng", "disappointment": "Sự thất vọng",
        "disaster": "Thảm họa", "disastrous": "Tai hại", "disc": "Đĩa", "discard": "Loại bỏ", "discharge": "Thải ra, giải ngũ",
        "discipline": "Kỷ luật", "disclose": "Tiết lộ", "disclosure": "Sự tiết lộ", "discount": "Giảm giá", "discourage": "Làm nản lòng",
        "discourse": "Diễn thuyết", "discover": "Khám phá", "discovery": "Sự khám phá", "discretion": "Sự thận trọng", "discriminate": "Phân biệt đối xử",
        "discrimination": "Sự phân biệt đối xử", "discuss": "Thảo luận", "discussion": "Cuộc thảo luận", "disease": "Bệnh tật", "dish": "Món ăn",
        "dishonest": "Không trung thực", "dislike": "Không thích", "dismiss": "Sa thải, bác bỏ", "dismissal": "Sự sa thải", "disorder": "Rối loạn",
        "displace": "Thay thế, chiếm chỗ", "display": "Hiển thị", "disposal": "Sự vứt bỏ", "dispose": "Vứt bỏ", "dispute": "Tranh chấp",
        "disrupt": "Làm gián đoạn", "disruption": "Sự gián đoạn", "dissolve": "Hòa tan", "distance": "Khoảng cách", "distant": "Xa cách",
        "distinct": "Khác biệt", "distinction": "Sự khác biệt", "distinctive": "Đặc biệt", "distinguish": "Phân biệt", "distort": "Xuyên tạc",
        "distract": "Làm xao nhãng", "distress": "Cực khổ, đau khổ", "distribute": "Phân phối", "distribution": "Sự phân phối",
        "distributor": "Nhà phân phối", "district": "Quận, huyện", "disturb": "Làm phiền", "disturbing": "Đáng lo ngại", "dive": "Lặn",
        "diverse": "Đa dạng", "diversity": "Sự đa dạng", "divert": "Làm chuyển hướng", "divide": "Chia", "divine": "Thần thánh",
        "division": "Sự phân chia", "divorce": "Ly hôn", "divorced": "Đã ly hôn", "do": "Làm", "doctor": "Bác sĩ",
        "doctrine": "Học thuyết", "document": "Tài liệu", "documentary": "Phim tài liệu", "documentation": "Tài liệu hướng dẫn", "dog": "Con chó",
        "doll": "Búp bế", "domain": "Miền, lĩnh vực", "domestic": "Trong nước", "dominance": "Sự thống trị", "dominant": "Thống trị",
        "dominate": "Thống trị", "donation": "Sự quyên góp", "donor": "Người hiến tặng", "door": "Cửa", "dose": "Liều lượng",
        "dot": "Chấm", "double": "Gấp đôi", "doubt": "Nghi ngờ", "down": "Xuống", "download": "Tải xuống",
        "downstairs": "Tầng dưới", "downward": "Đi xuống", "dozen": "Tá (12)", "draft": "Bản thảo", "drag": "Kéo",
        "drain": "Thoát nước", "drama": "Kịch", "dramatic": "Kịch tính", "dramatically": "Đáng kể", "draw": "Vẽ, kéo",
        "drawing": "Bản vẽ", "dream": "Giấc mơ", "dress": "Váy", "dressed": "Ăn mặc", "drift": "Trôi dạt",
        "drill": "Khoan, tập luyện", "drink": "Uống", "drive": "Lái xe", "driver": "Tài xế", "driving": "Lái xe",
        "drop": "Rơi, giọt", "drought": "Hạn hán", "drown": "Chết đuối", "drug": "Thuốc, ma túy", "drum": "Cái trống",
        "drunk": "Say rượu", "dry": "Khô", "dual": "Kép", "dub": "Lồng tiếng", "due": "Đến hạn",
        "duke": "Công tước", "dull": "Xỉn màu, buồn tẻ", "dumb": "Câm, ngớ ngẩn", "dump": "Đổ rác", "duo": "Bộ đôi",
        "duration": "Khoảng thời gian", "during": "Trong lúc", "dust": "Bụi", "duty": "Nhiệm vụ, thuế", "dynamic": "Năng động",
        "gain": "Đạt được, tăng trưởng", "galaxy": "Thiên hà", "gallery": "Ngõ ảnh, phòng trưng bày", "gallon": "Gallon (đơn vị đo)", "gamble": "Đánh bạc",
        "gambling": "Sự đánh bạc", "game": "Trò chơi", "gaming": "Chơi game", "gang": "Băng nhóm", "gap": "Khoảng cách, lỗ hổng",
        "garage": "Nhà để xe", "garden": "Vườn", "gas": "Khí, xăng", "gate": "Cổng", "gather": "Thu thập",
        "gathering": "Cuộc tụ họp", "gauge": "Máy đo", "gay": "Đồng tính", "gaze": "Cái nhìn chằm chằm", "gear": "Bánh răng, thiết bị",
        "gender": "Giới tính", "gene": "Gen", "general": "Chung, tổng quát", "generalize": "Khái quát hóa", "generally": "Nói chung",
        "generate": "Tạo ra", "generation": "Thế hệ", "generic": "Chung, không có thương hiệu", "generous": "Hào phóng", "genetic": "Thuộc di truyền",
        "genius": "Thiên tài", "genocide": "Diệt chủng", "genre": "Thể loại", "gentle": "Nhẹ nhàng", "gentleman": "Quý ông",
        "gently": "Nhẹ nhàng", "genuine": "Thật, chính hãng", "genuinely": "Thật sự", "geography": "Địa lý", "gesture": "Cử chỉ",
        "get": "Lấy, nhận", "ghost": "Con ma", "giant": "Khổng lồ", "gift": "Quà tặng", "gifted": "Có năng khiếu",
        "girl": "Cô gái", "girlfriend": "Bạn gái", "give": "Cho", "glad": "Vui mừng", "glance": "Liếc nhìn",
        "glass": "Thủy tinh, cái ly", "glasses": "Kính mắt", "gleam": "Tia sáng", "glide": "Trượt", "glimpse": "Nhìn thoáng qua",
        "global": "Toàn cầu", "globalization": "Toàn cầu hóa", "globe": "Quả cầu, thế giới", "glorious": "Vinh quang", "glory": "Vinh quang",
        "glove": "Găng tay", "glow": "Ánh sáng rực rỡ", "glue": "Keo dán", "go": "Đi", "goal": "Mục tiêu",
        "goat": "Con dê", "god": "Thần, Chúa", "gold": "Vàng", "golden": "Bằng vàng", "golf": "Gôn",
        "good": "Tốt", "goodbye": "Tạm biệt", "goodness": "Sự tốt lành", "goods": "Hàng hóa", "gorgeous": "Tuyệt đẹp",
        "govern": "Cai trị", "governance": "Sự quản trị", "government": "Chính phủ", "governor": "Thống đốc", "grab": "Chộp lấy",
        "grace": "Vẻ duyên dáng", "graceful": "Duyên dáng", "grade": "Lớp, điểm số", "gradually": "Dần dần", "graduate": "Tốt nghiệp",
        "graduation": "Lễ tốt nghiệp", "grain": "Hạt", "grand": "Hùng vĩ, lớn", "grandchild": "Cháu", "granddaughter": "Cháu gái",
        "grandfather": "Ông", "grandmother": "Bà", "grandparent": "Ông bà", "grandson": "Cháu trai", "grant": "Trợ cấp, ban cho",
        "grape": "Quả nho", "graph": "Đồ thị", "graphics": "Đồ họa", "grasp": "Nắm bắt", "grass": "Cỏ",
        "grateful": "Biết ơn", "grave": "Ngôi mộ, nghiêm trọng", "gravity": "Trọng lực", "gray": "Màu xám", "great": "Tuyệt vời",
        "greatly": "Rất nhiều", "greed": "Sự tham lam", "greedy": "Tham lam", "green": "Màu xanh lá cây", "greeting": "Lời chào",
        "grid": "Lưới", "grief": "Nỗi đau buồn", "grin": "Cười toe toét", "grind": "Nghiền", "grip": "Nắm chặt",
        "grocery": "Cửa hàng tạp hóa", "gross": "Tổng, gớm ghiếc", "ground": "Mặt đất", "group": "Nhóm", "grow": "Phát triển, trồng",
        "growth": "Sự phát triển", "guarantee": "Bảo hành, đảm bảo", "guard": "Bảo vệ", "guerrilla": "Du kích", "guess": "Đoán",
        "guest": "Khách", "guidance": "Sự hướng dẫn", "guide": "Hướng dẫn", "guideline": "Hướng dẫn, nguyên tắc", "guilt": "Tội lỗi",
        "guilty": "Có tội", "guitar": "Đàn ghi-ta", "gun": "Súng", "gut": "Ruột, can đảm", "guy": "Anh chàng", "gym": "Phòng tập gym",
        "habit": "Thói quen", "habitat": "Môi trường sống", "hail": "Mưa đá", "hair": "Tóc", "half": "Nửa",
        "halfway": "Nửa chừng", "hall": "Hội trường, sảnh", "halt": "Tạm dừng", "hand": "Bàn tay", "handful": "Một ít, đầy tay",
        "handle": "Xử lý, tay cầm", "handling": "Sự xử lý", "handy": "Tiện lợi", "hang": "Treo", "happen": "Xảy ra",
        "happening": "Sự việc đang xảy ra", "happily": "Hạnh phúc", "happiness": "Hạnh phúc", "happy": "Hạnh phúc", "harassment": "Sự quấy rối",
        "harbour": "Cảng", "hard": "Cứng, khó", "hardly": "Hầu như không", "hardship": "Sự gian khổ", "hardware": "Phần cứng",
        "harm": "Gây hại", "harmful": "Có hại", "harmonious": "Hài hòa", "harmony": "Sự hài hòa", "harsh": "Khắc nghiệt",
        "harvest": "Thu hoạch", "hat": "Cái mũ", "hate": " Ghét", "hatred": "Sự căm ghét", "haunt": "Ám ảnh",
        "have": "Có", "hawk": "Chim ưng", "hazard": "Mối nguy hiểm", "he": "Anh ấy", "head": "Đầu",
        "headache": "Đau đầu", "headline": "Tiêu đề", "headquarters": "Trụ sở chính", "heal": "Chữa lành", "health": "Sức khỏe",
        "healthcare": "Chăm sóc sức khỏe", "healthy": "Khỏe mạnh", "heap": "Đống", "hear": "Nghe", "hearing": "Thính giác, phiên tòa",
        "heart": "Trái tim", "heat": "Nhiệt", "heater": "Máy sưởi", "heating": "Hệ thống sưởi", "heaven": "Thiên đường",
        "heavy": "Nặng", "heavily": "Nặng nề", "hedge": "Hàng rào cây", "heel": "Gót chân", "height": "Chiều cao",
        "heighten": "Nâng cao", "helicopter": "Trực thăng", "hell": "Địa ngục", "hello": "Xin chào", "helmet": "Mũ bảo hiểm",
        "help": "Giúp đỡ", "helpful": "Có ích", "hence": "Do đó", "her": "Cô ấy (tân ngữ/sở hữu)", "herb": "Thảo mộc",
        "herd": "Đàn (gia súc)", "here": "Ở đây", "heritage": "Di sản", "hero": "Anh hùng", "heroic": "Anh hùng",
        "herself": "Chính cô ấy", "hesitate": "Do dự", "hey": "Này", "hi": "Chào", "hide": "Trốn, ẩn nấp",
        "hierarchy": "Hệ thống phân cấp", "high": "Cao", "high-tech": "Công nghệ cao", "highlight": "Làm nổi bật", "highly": "Rất, cao",
        "highway": "Đường cao tốc", "hilarious": "Vui nhộn", "hill": "Đồi", "him": "Anh ấy (tân ngữ)", "himself": "Chính anh ấy",
        "hint": "Gợi ý", "hip": "Hông", "hire": "Thuê", "his": "Của anh ấy", "historic": "Có tính lịch sử",
        "historical": "Thuộc lịch sử", "history": "Lịch sử", "hit": "Đánh, cú va chạm", "hobby": "Sở thích", "hockey": "Khúc côn cầu",
        "hold": "Giữ", "holder": "Người giữ", "holding": "Sự nắm giữ, cổ phần", "hole": "Cái lỗ", "holiday": "Kỳ nghỉ",
        "hollow": "Rỗng", "holy": "Thánh", "home": "Nhà", "homeland": "Quê hương", "homeless": "Vô gia cư",
        "homemade": "Tự làm", "homework": "Bài tập về nhà", "homicide": "Vụ giết người", "honest": "Trung thực", "honesty": "Sự trung thực",
        "honey": "Mật ong", "honor": "Danh dự", "honourable": "Đáng kính", "hook": "Cái móc", "hope": "Hy vọng",
        "hopeful": "Đầy hy vọng", "hopefully": "Hy vọng là", "hopeless": "Tuyệt vọng", "horizon": "Chân trời", "horizontal": "Ngang",
        "hormone": "Hoóc môn", "horn": "Sừng, còi", "horrible": "Kinh khủng", "horror": "Kinh dị", "horse": "Con ngựa",
        "hospital": "Bệnh viện", "hospitality": "Sự hiếu khách", "host": "Chủ nhà", "hostage": "Con tin", "hostile": "Thù địch",
        "hostility": "Sự thù địch", "hot": "Nóng", "hotel": "Khách sạn", "hour": "Giờ", "house": "Ngôi nhà",
        "household": "Hộ gia đình", "housing": "Nhà ở", "how": "Như thế nào", "however": "Tuy nhiên", "huge": "Khổng lồ",
        "human": "Con người", "humanitarian": "Nhân đạo", "humanity": "Nhân loại", "humble": "Khiêm tốn", "humiliation": "Sự sỉ nhục",
        "humorous": "Hài hước", "humour": "Sự hài hước", "hundred": "Trăm", "hunger": "Sự đói khát", "hungry": "Đói",
        "hunt": "Săn bắn", "hunter": "Thợ săn", "hunting": "Sự săn bắn", "hurdle": "Rào cản", "hurry": "Nhanh chóng",
        "hurt": "Làm đau", "husband": "Chồng", "hybrid": "Lai tạo", "hydrogen": "Hydro", "hypothesis": "Giả thuyết",
        "hypothetical": "Giả thuyết",
        "ice": "Băng, đá", "ice-cream": "Kem", "icon": "Biểu tượng", "idea": "Ý tưởng", "ideal": "Lý tưởng",
        "identical": "Giống hệt", "identification": "Sự nhận dạng", "identify": "Xác định", "identity": "Bản sắc, danh tính", "ideological": "Thuộc hệ tư tưởng",
        "ideology": "Hệ tư tưởng", "idiot": "Kẻ ngốc", "if": "Nếu", "ignite": "Đốt cháy", "ignorance": "Sự thiếu hiểu biết",
        "ignore": "Phớt lờ", "ill": "Ốm", "illegal": "Bất hợp pháp", "illness": "Căn bệnh", "illusion": "Ảo giác",
        "illustrate": "Minh họa", "illustration": "Sự minh họa", "image": "Hình ảnh", "imagery": "Hình tượng", "imaginary": "Tưởng tượng",
        "imagination": "Sự tưởng tượng", "imagine": "Tưởng tượng", "immediate": "Lập tức", "immediately": "Ngay lập tức", "immense": "Bao la",
        "immigrant": "Người nhập cư", "immigration": "Sự nhập cư", "imminent": "Sắp xảy ra", "immune": "Miễn dịch", "impact": "Tác động",
        "impatient": "Thiếu kiên nhẫn", "implement": "Thực hiện", "implementation": "Sự thực hiện", "implication": "Ngụ ý, hệ quả", "imply": "Ngụ ý",
        "import": "Nhập khẩu", "importance": "Tầm quan trọng", "important": "Quan trọng", "impose": "Áp đặt", "impossible": "Không thể",
        "impress": "Gây ấn tượng", "im        "keep": "Giữ", "keeper": "Người canh giữ", "key": "Chìa khóa, bàn phím", "keyboard": "Bàn phím", "kick": "Đá",
        "kid": "Đứa trẻ", "kidney": "Thận", "kill": "Giết", "killer": "Kẻ sát nhân", "killing": "Sự giết chóc",
        "kilogram": "Ki-lô-gam", "kilometer": "Ki-lô-mét", "kind": "Loại, tử tế", "kindness": "Sự tử tế", "king": "Vua",
        "kingdom": "Vương quốc", "kiss": "Hôn", "kit": "Bộ dụng cụ", "kitchen": "Nhà bếp", "knee": "Đầu gối",
        "knife": "Con dao", "knock": "Gõ cửa", "knot": "Nút thắt", "know": "Biết", "knowledge": "Kiến thức",
        "label": "Nhãn hiệu", "laboratory": "Phòng thí nghiệm", "lack": "Thiếu sót", "lady": "Quý bà", "lake": "Hồ",
        "lamb": "Cừu con", "land": "Đất liền, hạ cánh", "landscape": "Phong cảnh", "lane": "Làn đường, dòng", "language": "Ngôn ngữ",
        "laptop": "Máy tính xách tay", "large": "Lớn", "largely": "Phần lớn", "last": "Cuối cùng, kéo dài", "late": "Muộn",
        "lately": "Gần đây", "later": "Sau đó", "latest": "Mới nhất", "laugh": "Cười", "laughter": "Tiếng cười",
        "launch": "Ra mắt, phóng", "law": "Luật pháp", "lawsuit": "Vụ kiện", "lawyer": "Luật sư", "lay": "Đặt, để",
        "layer": "Lớp", "lead": "Dẫn dắt, chì", "leader": "Người lãnh đạo", "leadership": "Khả năng lãnh đạo", "leading": "Hàng đầu",
        "leaf": "Lá cây", "league": "Liên minh, giải đấu", "leak": "Rò rỉ", "lean": "Dựa vào, nghiêng", "learn": "Học",
        "learned": "Có học thức", "learner": "Người học", "learning": "Sự học", "least": "Ít nhất", "leather": "Da",
        "leave": "Rời đi, nghỉ phép", "lecture": "Bài giảng", "left": "Bên trái, rời đi (V2)", "leg": "Chân", "legacy": "Di sản",
        "legal": "Hợp pháp", "legend": "Huyền thoại", "legislation": "Pháp luật", "legitimate": "Hợp pháp, chính đáng", "leisure": "Giải trí, thời gian rỗi",
        "lemon": "Quả chanh", "lend": "Cho vay", "length": "Chiều dài", "less": "Ít hơn", "lesson": "Bài học",
        "let": "Cho phép, để", "letter": "Thư, chữ cái", "level": "Mức độ", "lever": "Đòn bẩy", "liability": "Trách nhiệm pháp lý",
        "liable": "Có khả năng", "liberal": "Tự do, phóng khoáng", "liberty": "Tự do", "library": "Thư viện", "licence": "Giấy phép",
        "license": "Cấp phép", "lick": "Liếm", "lid": "Nắp", "lie": "Nói dối, nằm", "life": "Cuộc sống",
        "lifestyle": "Lối sống", "lifetime": "Cả cuộc đời", "lift": "Nâng lên, thang máy", "light": "Ánh sáng, nhẹ", "lighting": "Ánh sáng, illumination",
        "like": "Thích, giống như", "likelihood": "Khả năng xảy ra", "likely": "Có khả năng", "limit": "Giới hạn", "limitation": "Sự hạn chế",
        "limited": "Hữu hạn", "line": "Dòng, đường kẻ", "link": "Liên kết", "lion": "Sư tử", "lip": "Môi",
        "liquid": "Chất lỏng", "list": "Danh sách", "listen": "Nghe", "listener": "Người nghe", "literature": "Văn học",
        "litre": "Lít", "little": "Ít, nhỏ", "live": "Sống, trực tiếp", "lively": "Sống động", "liver": "Gan",
        "living": "Sự sống, sống", "load": "Tải trọng", "loan": "Khoản vay", "local": "Địa phương", "locate": "Xác định vị trí",
        "location": "Vị trí", "lock": "Khóa", "log": "Nhật ký, gỗ", "logic": "Lý luận", "logical": "Hợp lý",
        "lonely": "Cô đơn", "long": "Dài", "long-term": "Dài hạn", "look": "Nhìn", "loop": "Vòng lặp",
        "loose": "Lỏng lẻo", "lord": "Chúa tể, quý ngài", "lose": "Mất, thất bại", "loss": "Sự mất mát", "lost": "Bị mất, lạc",
        "lot": "Nhiều", "loud": "To (âm thanh)", "love": "Yêu", "lovely": "Đáng yêu", "lover": "Người yêu",
        "low": "Thấp", "loyal": "Trung thành", "loyalty": "Lòng trung thành", "luck": "May mắn", "lucky": "May mắn",
        "luggage": "Hành lý", "lump": "Cục, tảng", "lunch": "Bữa trưa", "lung": "Phổi", "luxury": "Sang trọng",
        "machine": "Máy móc", "machinery": "Máy móc thiết bị", "mad": "Điên", "magazine": "Tạp chí", "magic": "Phép thuật",
        "magical": "Thần kỳ", "magistrate": "Thẩm phán", "magnetic": "Thuộc nam châm", "magnitude": "Tầm vóc, cường độ", "mail": "Thư",
        "main": "Chính", "mainland": "Đất liền", "mainly": "Chủ yếu", "mainstream": "Xu hướng chủ đạo", "maintain": "Duy trì",
        "maintenance": "Sự bảo trì", "major": "Chính, chuyên ngành", "majority": "Đa số", "make": "Làm, tạo ra", "make-up": "Đồ trang điểm, cấu tạo",
        "male": "Nam", "mall": "Trung tâm mua sắm", "man": "Đàn ông", "manage": "Quản lý", "management": "Sự quản lý",
        "manager": "Người quản lý", "mandate": "Lệnh, chỉ thị", "mandatory": "Bắt buộc", "manifest": "Biểu lộ, bản kê khai", "manipulate": "Thao túng",
        "manipulation": "Sự thao túng", "manner": "Cách thức, thái độ", "manufacture": "Sản xuất", "manufacturing": "Ngành sản xuất", "manuscript": "Bản thảo",
        "many": "Nhiều", "map": "Bản đồ", "marathon": "Cuộc đua marathon", "march": "Diễu hành, tháng Ba", "margin": "Lề, lợi nhuận biên",
        "marginal": "Không đáng kể, ở lề", "marine": "Thuộc biển", "mark": "Dấu vết, điểm", "market": "Thị trường", "marketing": "Tiếp thị",
        "marketplace": "Sàn giao dịch", "marriage": "Hôn nhân", "married": "Đã kết hôn", "marry": "Kết hôn", "marvelous": "Kỳ diệu",
        "mass": "Quần chúng, khối lượng", "massacre": "Thảm sát", "massive": "Đồ sộ, to lớn", "master": "Chủ nhân, bậc thầy", "masterpiece": "Kiệt tác",
        "match": "Phù hợp, trận đấu, diêm", "matching": "Phù hợp", "mate": "Bạn, phối giống", "material": "Vật liệu, tài liệu", "mathematical": "Thuộc toán học",
        "mathematics": "Toán học", "maths": "Toán học", "matter": "Vấn đề, vật chất", "maximum": "Tối đa", "may": "Có thể, tháng Năm",
        "maybe": "Có lẽ", "mayor": "Thị trưởng", "me": "Tôi", "meadow": "Đồng cỏ", "meal": "Bữa ăn",
        "mean": "Có nghĩa là, keo kiệt", "meaning": "Ý nghĩa", "meaningful": "Có ý nghĩa", "means": "Phương tiện, cách thức", "meantime": "Trong khi đó",
        "meanwhile": "Trong khi đó", "measure": "Biện pháp, đo lường", "measurement": "Sự đo lường", "meat": "Thịt", "mechanic": "Thợ máy",
        "mechanical": "Thuộc cơ khí", "mechanism": "Cơ chế", "medal": "Huy chương", "media": "Phương tiện truyền thông", "medical": "Thuộc y tế",
        "medication": "Thuốc", "medicine": "Thuốc, y học", "medieval": "Thuộc thời trung cổ", "mediocre": "Tầm thường", "meditate": "Thiền",
        "meditation": "Sự thiền định", "medium": "Trung bình, phương tiện", "meet": "Gặp gỡ", "meeting": "Cuộc họp", "melody": "Giai điệu",
        "melt": "Tan chảy", "member": "Thành viên", "membership": "Tư cách thành viên", "memo": "Bản ghi nhớ", "memoir": "Hồi ký",
        "memorable": "Đáng nhớ", "memorial": "Đài tưởng niệm", "memory": "Bộ nhớ, trí nhớ", "mental": "Thuộc tâm thần, trí óc", "mention": "Đề cập",
        "mentor": "Người cố vấn", "menu": "Thực đơn", "merchant": "Thương gia", "mercy": "Lòng khoan dung", "mere": "Chỉ là",
        "merely": "Chỉ", "merit": "Xứng đáng, công trạng", "mess": "Sự bừa bộn", "message": "Tin nhắn, thóng điệp", "metal": "Kim loại",
        "metaphor": "Phép ẩn dụ", "method": "Phương pháp", "methodology": "Phương pháp luận", "meticulous": "Tỉ mỉ", "metre": "Mét",
        "metric": "Hệ mét", "middle": "Ở giữa", "midnight": "Nửa đêm", "might": "Có thể, sức mạnh", "migrant": "Người di cư",
        "migration": "Sự di cư", "mild": "Nhẹ, ôn hòa", "mile": "Dặm", "military": "Thuộc quân sự", "milk": "Sữa",
        "mill": "Nhà máy, cối xay", "million": "Triệu", "mind": "Tâm trí, phiền", "mine": "Của tôi, mầm đá", "miner": "Thợ mỏ",
        "mineral": "Khoáng chất", "minimal": "Tối thiểu", "minimize": "Giảm thiểu", "minimum": "Tối thiểu", "mining": "Khai thác mỏ",
        "minister": "Bộ trưởng", "ministry": "Bộ", "minor": "Nhỏ, không quan trọng", "minority": "Thiểu số", "mint": "Bạc hà, xưởng đúc tiền",
        "minus": "Trừ, âm", "minute": "Phút, mỉ tỉ", "miracle": "Phép màu", "mirror": "Gương", "misery": "Sự khốn khổ",
        "misleading": "Gây hiểu lầm", "miss": "Nhỡ, bỏ lỡ, thiếu", "missing": "Bị mất, thiếu", "mission": "Nhiệm vụ, sứ mệnh", "mistake": "Lỗi",
        "mistaken": "Sai lầm", "mix": "Trộn", "mixed": "Hỗn hợp", "mixture": "Hỗn hợp", "moan": "Than vãn",
        "mobile": "Di động", "mobility": "Tính di động", "mode": "Chế độ, cách thức", "model": "Mô hình, người mẫu", "moderate": "Vừa phải, ôn hòa",
        "modern": "Hiện đại", "modest": "Khiêm tốn", "modification": "Sự sửa đổi", "modify": "Sửa đổi", "moist": "Ẩm ướt",
        "moisture": "Độ ẩm", "moment": "Khoảnh khắc", "momentary": "Chốc lát", "momentum": "Đà, động năng", "Monday": "Thứ Hai",
        "money": "Tiền", "monitor": "Giám sát, màn hình", "monk": "Nhà sư", "monkey": "Con khỉ", "monopoly": "Độc quyền",
        "monster": "Quái vật", "month": "Tháng", "monthly": "Hàng tháng", "monument": "Đài kỷ niệm", "mood": "Tâm trạng",
        "moon": "Mặt trăng", "moral": "Thuộc đạo đức", "morale": "Tinh thần", "morality": "Đạo đức", "more": "Nhiều hơn",
        "moreover": "Hơn nữa", "morning": "Buổi sáng", "mortgage": "Thế chấp", "mosque": "Nhà thờ Hồi giáo", "most": "Nhất, đa số",
        "mostly": "Hầu hết", "mother": "Mẹ", "motif": "Mô típ, chủ đề", "motion": "Chuyển động", "motivate": "Thúc đẩy",
        "motivation": "Động lực", "motive": "Động cơ", "motor": "Động cơ", "motorcycle": "Xe máy", "motorist": "Người lái xe",
        "mount": "Leo lên, núi", "mountain": "Núi", "mourning": "Sự tang lễ", "mouse": "Con chuột", "mouth": "Miệng",
        "move": "Di chuyển", "movement": "Sự di chuyển", "movie": "Phim", "much": "Nhiều", "mud": "Bùn",
        "multiple": "Nhiều, phức hợp", "multiply": "Nhân lên", "multitude": "Đám đông, vô số", "mum": "Mẹ", "municipal": "Thuộc thành phố",
        "murder": "Giết người", "murderer": "Kẻ sát nhân", "muscle": "Cơ bắp", "museum": "Bàng tàng", "music": "Âm nhạc",
        "musical": "Thuộc âm nhạc, nhạc kịch", "musician": "Nhạc sĩ", "muslim": "Người Hồi giáo", "must": "Phải", "mutual": "Lẫn nhau",
        "my": "Của tôi", "mysterious": "Bí ẩn", "mystery": "Điều bí ẩn", "myth": "Thần thoại, huyền thoại",
        "nail": "Móng tay, đinh", "naked": "Trần trụi", "name": "Tên", "namely": "Cụ thể là", "narrative": "Chuyện kể, tường thuật",
        "narrow": "Hẹp", "nasty": "Khó chịu, xấu xí", "nation": "Quốc gia", "national": "Thuộc quốc gia", "nationwide": "Toàn quốc",
        "native": "Bản địa", "natural": "Tự nhiên", "naturally": "Một cách tự nhiên", "nature": "Thiên nhiên, bản chất", "naval": "Thuộc hải quân",
        "navigation": "Sự điều hướng", "navy": "Hải quân", "near": "Gần", "nearby": "Gần đó", "nearly": "Gần như",
        "neat": "Gọn gàng", "necessarily": "Nhất thiết", "necessary": "Cần thiết", "necessity": "Sự cần thiết", "neck": "Cổ",
        "need": "Cần", "needle": "Cây kim", "negative": "Tiêu cực, phủ định", "neglect": "Thờ ơ, sao nhãng", "negotiate": "Đàm phán",
        "negotiation": "Sự đàm phán", "neighbor": "Hàng xóm", "neighborhood": "Khu phố, lân cận", "neighborly": "Thân thiện (như hàng xóm)", "neither": "Không phải người này cũng không phải người kia",
        "nephew": "Cháu trai", "nerve": "Dây thần kinh", "nervous": "Lo lắng, thuộc thần kinh", "nest": "Tổ", "net": "Lưới, ròng (thu nhập)",
        "network": "Mạng lưới", "neutral": "Trung lập", "never": "Không bao giờ", "nevertheless": "Tuy nhiên", "new": "Mới",
        "newly": "Gần đây", "news": "Tin tức", "newsletter: Bản tin", "newspaper": "Báo", "next": "Tiếp theo",
        "next to": "Bên cạnh", "nice": "Đẹp, tử tế", "niche": "Phân khúc, hốc", "nick": "Vết khía", "nickname": "Tên biệt danh",
        "niece": "Cháu gái", "night": "Đêm", "nightmare": "Ác mộng", "nine": "Chín", "nineteen": "Mười chín",
        "ninety": "Chín mươi", "ninth": "Thứ chín", "no": "Không", "nobility": "Quý tộc, cao quý", "noble": "Cao quý, quý tộc",
        "nobody": "Không ai", "nod": "Gật đầu", "noise": "Tiếng ồn", "noisy": "Ồn ào", "nominal": "Danh nghĩa, nhỏ bé",
        "nominate": "Đề cử", "nomination": "Sự đề cử", "nominee": "Người được đề cử", "none": "Không ai, không cái gì", "nonetheless": "Tuy nhiên, mặc dù vậy",
        "non-profit": "Phi lợi nhuận", "nonsense": "Vô lý, vớ vẩn", "noon": "Trưa, nửa ngày", "nor": "Cũng không", "norm": "Định mức, chuẩn mực",
        "normal": "Bình thường", "normally": "Thông thường", "north": "Phía bắc", "northern": "Thuộc phía bắc", "nose": "Mũi",
        "not": "Không", "notable": "Đáng chú ý", "notably": "Đáng chú ý là", "note": "Ghi chú, tờ tiền, nốt nhạc", "notebook": "Vở ghi chép, máy tính xách tay",
        "nothing": "Không có gì", "notice": "Thông báo, chú ý", "noticeable": "Đáng chú ý", "notify": "Thông báo", "notion": "Khái niệm, quan điểm",
        "notorious": "Khét tiếng, tai tiếng", "novel": "Tiểu thuyết, mới lạ", "novelist": "Tiểu thuyết gia", "novelty": "Sự mới lạ, vật mới lạ", "November": "Tháng Mười Một",
        "now": "Bây giờ", "nowadays": "Ngày nay", "nowhere": "Không nơi nào", "nuclear": "Thuộc hạt nhân", "nuisance": "Sự phiền tóai",
        "number": "Số", "numerous": "Nhiều", "nurse": "Y tá, nuôi dưỡng", "nursery": "Nhà trẻ, vườn ươm", "nursing": "Sự chăm sóc điều dưỡng",
        "nurture": "Nuôi dưỡng", "nut": "Hạt, đai ốc", "nutrient": "Chất dinh dưỡng", "nutrition": "Dinh dưỡng", "nylon": "Ni lông",
    }
g", "eight": "Tám", "eighteen": "Mười tám",
        "eighty": "Tám mươi", "either": "Hoặc", "elaborate": "Tỉ mỉ", "elbow": "Khuỷu tay", "elder": "Người lớn tuổi hơn",
        "elderly": "Người cao tuổi", "elect": "Bầu chọn", "election": "Cuộc bầu cử", "electoral": "Thuộc bầu cử", "electric": "Điện",
        "electrical": "Thuộc về điện", "electricity": "Điện", "electronic": "Điện tử", "electronics": "Điện tử học", "elegant": "Lịch lãm, trang nhã",
        "element": "Yếu tố", "elementary": "Sơ cấp", "elephant": "Con voi", "elevate": "Nâng lên", "elevation": "Sự nâng lên",
        "eleven": "Mười một", "eligible": "Đủ điều kiện", "eliminate": "Loại bỏ", "elite": "Ưu tú", "else": "Khác",
        "elsewhere": "Nơi khác", "email": "Thư điện tử", "embark": "Lên tàu, bắt đầu", "embarrassed": "Ngượng ngùng", "embarrassing": "Gây xấu hổ",
        "embarrassment": "Sự ngượng ngùng", "embassy": "Đại sứ quán", "embed": "Nhúng", "embody": "Hiện thân", "embrace": "Ôm, chấp nhận",
        "emerge": "Nổi lên", "emergence": "Sự nổi lên", "emergency": "Trường hợp khẩn cấp", "emission": "Sự phát thải", "emotion": "Cảm xúc",
        "emotional": "Thuộc cảm xúc", "emotionally": "Về mặt cảm xúc", "emphasis": "Sự nhấn mạnh", "emphasize": "Nhấn mạnh", "empire": "Đế chế",
        "empirical": "Theo kinh nghiệm", "employ": "Thuê làm", "employee": "Nhân viên", "employer": "Người chủ", "employment": "Việc làm",
        "empower": "Trao quyền", "empty": "Trống rỗng", "enable": "Cho phép", "enact": "Ban hành", "encompass": "Bao gồm",
        "encounter": "Gặp gỡ", "encourage": "Khuyến khích", "encouragement": "Sự khuyến khích", "encouraging": "Mang tính khuyến khích", "end": "Kết thúc",
        "endanger": "Gây nguy hiểm", "endeavour": "Sự nỗ lực", "ending": "Sự kết thúc", "endless": "Vô tận", "endorse": "Xác nhận, ủng hộ",
        "endorsement": "Sự xác nhận", "endure": "Chịu đựng", "enemy": "Kẻ thù", "energy": "Năng lượng", "enforce": "Thực thi",
        "enforcement": "Sự thực thi", "engage": "Tham gia", "engaged": "Đã đính hôn, tham gia", "engagement": "Sự tham gia, đính hôn", "engine": "Động cơ",
        "engineer": "Kỹ sư", "engineering": "Kỹ thuật", "enhance": "Nâng cao", "enjoy": "Thưởng thức", "enjoyable": "Thú vị",
        "enormous": "To lớn", "enough": "Đủ", "enquire": "Hỏi", "enquiry": "Sự yêu cầu", "enrich": "Làm phong phú",
        "enrol": "Ghi danh", "ensue": "Kéo theo", "ensure": "Đảm bảo", "enter": "Đi vào", "enterprise": "Doanh nghiệp",
        "entertain": "Giải trí", "entertainer": "Người làm giải trí", "entertaining": "Thú vị, giải trí", "entertainment": "Sự giải trí", "enthusiasm": "Sự nhiệt tình",
        "enthusiast": "Người nhiệt tình", "enthusiastic": "Nhiệt tình", "entire": "Toàn bộ", "entirely": "Hoàn toàn", "entitle": "Cho quyền",
        "entity": "Thực thể", "entrance": "Lối vào", "entrepreneur": "Doanh nhân", "entry": "Lối vào", "envelope": "Phong bì",
        "environment": "Môi trường", "environmental": "Thuộc môi trường", "environmentalist": "Nhà môi trường", "envision": "Hình dung", "envy": "Ghen tị",
        "epidemic": "Dịch bệnh", "episode": "Tập phim", "equal": "Công bằng, bằng nhau", "equality": "Sự bình đẳng", "equally": "Một cách bình đẳng",
        "equation": "Phương trình", "equip": "Trang bị", "equipment": "Thiết bị", "equivalent": "Tương đương", "era": "Kỷ nguyên",
        "erect": "Dựng lên", "erode": "Ăn mòn", "erosion": "Sự xói mòn", "error": "Lỗi", "erupt": "Phun trào",
        "escalate": "Leo thang", "escape": "Thoát khỏi", "especially": "Đặc biệt", "essay": "Bài tiểu luận", "essence": "Bản chất",
        "essential": "Thiết yếu", "essentially": "Về bản chất", "establish": "Thiết lập", "establishment": "Sự thiết lập", "estate": "Bất động sản",
        "estimate": "Ước tính", "estimation": "Sự ước tính", "eternal": "Vĩnh cửu", "ethic": "Đạo đức", "ethical": "Thuộc đạo đức",
        "ethics": "Đạo đức học", "ethnic": "Thuộc dân tộc", "euro": "Đồng Euro", "evacuate": "Sơ tán", "evaluate": "Đánh giá",
        "evaluation": "Sự đánh giá", "evaporate": "Bay hơi", "eve": "Đêm trước", "even": "Thậm chí, chẵn", "evening": "Buổi tối",
        "event": "Sự kiện", "eventual": "Cuối cùng", "eventually": "Cuối cùng", "ever": "Đã từng", "every": "Mỗi",
        "everybody": "Mọi người", "everyday": "Hàng ngày", "everyone": "Mọi người", "everything": "Mọi thứ", "everywhere": "Mọi nơi",
        "evict": "Đuổi đi", "evidence": "Bằng chứng", "evident": "Hiển nhiên", "evoke": "Gợi nhớ", "evolution": "Tiến hóa",
        "evolutionary": "Thuộc tiến hóa", "evolve": "Tiến hóa", "exacerbate": "Làm trầm trọng thêm", "exact": "Chính xác", "exactly": "Chính xác",
        "exaggerate": "Phóng đại", "exam": "Kỳ thi", "examination": "Kỳ thi, kiểm tra", "examine": "Kiểm tra", "example": "Ví dụ",
        "exasperate": "Làm bực tức", "exceed": "Vượt quá", "excellent": "Xuất sắc", "except": "Ngoại trừ", "exception": "Ngoại lệ",
        "exceptional": "Ngoại lệ, đặc biệt", "excess": "Sự dư thừa", "excessive": "Quá mức", "excessively": "Quá mức", "exchange": "Trao đổi",
        "excited": "Hào hứng", "excitement": "Sự hào hứng", "exciting": "Thú vị", "exclude": "Loại trừ", "exclusion": "Sự loại trừ",
        "exclusive": "Độc quyền", "exclusively": "Độc quyền", "excuse": "Lời xin lỗi, lý do", "execute": "Thi hành, hành hình", "execution": "Sự thực hiện",
        "executive": "Điều hành", "exemplify": "Minh họa", "exempt": "Miễn", "exercise": "Tập thể dục, bài tập", "exert": "Sử dụng sức lực",
        "exhale": "Thở ra", "exhaust": "Khí thải, làm mệt lử", "exhausted": "Kiệt sức", "exhausting": "Làm kiệt sức", "exhaustive": "Toàn diện",
        "exhibit": "Trưng bày", "exhibition": "Triển lãm", "exile": "Trực xuất, lưu đày", "exist": "Tồn tại", "existence": "Sự tồn tại",
        "exit": "Lối thoát", "exotic": "Kỳ lạ", "expand": "Mở rộng", "expansion": "Sự mở rộng", "expect": "Mong đợi",
        "expectancy": "Sự mong đợi", "expectation": "Kỳ vọng", "expedition": "Cuộc thám hiểm", "expel": "Trục xuất", "expenditure": "Chi phí",
        "expense": "Chi phí", "expensive": "Đắt tiền", "experience": "Kinh nghiệm", "experienced": "Có kinh nghiệm", "experiment": "Thí nghiệm",
        "experimental": "Thuộc thí nghiệm", "expert": "Chuyên gia", "expertise": "Chuyên môn", "expire": "Hết hạn", "explain": "Giải thích",
        "explanation": "Lời giải thích", "explicit": "Rõ ràng", "explicitly": "Một cách rõ ràng", "explode": "Nổ", "exploit": "Khai thác",
        "exploitation": "Sự khai thác", "exploration": "Sự thám hiểm", "explore": "Khám phá", "explosion": "Vụ nổ", "explosive": "Chất nổ",
        "export": "Xuất khẩu", "expose": "Tiếp xúc, phanh phui", "exposure": "Sự tiếp xúc", "express": "Bày tỏ", "expression": "Sự bày tỏ",
        "expressive": "Có sức diễn cảm", "exquisite": "Tinh tế", "extend": "Mở rộng", "extension": "Sự mở rộng", "extensive": "Rộng rãi",
        "extent": "Mức độ", "exterior": "Bên ngoài", "external": "Bên ngoài", "extra": "Thêm", "extract": "Chiết xuất",
        "extraordinary": "Phi thường", "extreme": "Cực đoan", "extremely": "Cực kỳ", "extremist": "Người cực đoan", "eye": "Mắt",
        "fabric": "Vải", "fabulous": "Thần thoại, tuyệt vời", "face": "Khuôn mặt", "face-to-face": "Trực tiếp", "facilitate": "Tạo điều kiện",
        "facility": "Cơ sở vật chất", "fact": "Sự thật", "faction": "Phái, bè phái", "factor": "Yếu tố", "factory": "Nhà máy",
        "faculty": "Khoa, khả năng", "fade": "Phai màu", "fail": "Thất bại", "failure": "Sự thất bại", "faint": "Ngất xỉu, mờ nhạt",
        "fair": "Công bằng, hội chợ", "fairly": "Khá", "fairness": "Sự công bằng", "faith": "Niềm tin", "faithful": "Trung thành",
        "fake": "Giả", "fall": "Rơi, mùa thu", "false": "Sai", "fame": "Sự nổi tiếng", "familiar": "Quen thuộc",
        "family": "Gia đình", "famine": "Nạn đói", "famous": "Nổi tiếng", "fan": "Người hâm mộ, cái quạt", "fancy": "Sang trọng, tưởng tượng",
        "fantastic": "Tuyệt vời", "fantasy": "Giả tưởng", "far": "Xa", "fare": "Giá vé", "farm": "Nông trại",
        "farmer": "Nông dân", "farming": "Công việc đồng áng", "fascinating": "Hấp dẫn", "fashion": "Thời trang", "fashionable": "Thời thượng",
        "fast": "Nanh", "fasten": "Buộc chặt", "fat": "Béo", "fatal": "Chết người", "fate": "Số phận",
        "father": "Cha", "fault": "Lỗi", "favour": "Sự ủng hộ, giúp đỡ", "favourable": "Thuận lợi", "favourite": "Yêu thích",
        "fear": "Sợ hãi", "feat": "Kỳ tích", "feather": "Lông vũ", "feature": "Tính năng", "federal": "Liên bang",
        "fee": "Lệ phí", "feed": "Cho ăn", "feedback": "Phản hồi", "feel": "Cảm thấy", "feeling": "Cảm xúc",
        "fellow": "Đồng chí, bạn", "female": "Nữ", "feminist": "Người theo chủ nghĩa nữ quyền", "fence": "Hàng rào", "festival": "Lễ hội",
        "fever": "Sốt", "few": "Ít", "fibre": "Chất xơ", "fiction": "Viễn tưởng", "field": "Lĩnh vực, cánh đồng",
        "fierce": "Hung dữ", "fifteen": "Mười lăm", "fifth": "Thứ năm", "fifty": "Năm mươi", "fight": "Chiến đấu",
        "fighting": "Sự chiến đấu", "figure": "Con số, nhân vật", "file": "Tệp, hồ sơ", "fill": "Làm đầy", "film": "Phim",
        "film-maker": "Nhà làm phim", "filter": "Bộ lọc", "final": "Cuối cùng", "finally": "Cuối cùng", "finance": "Tài chính",
        "financial": "Thuộc tài chính", "find": "Tìm thấy", "finding": "Phát hiện", "fine": "Tốt, tiền phạt", "finger": "Ngón tay",
        "finish": "Kết thúc", "fire": "Lửa, sa thải", "firearm": "Súng", "firefighter": "Lính cứu hỏa", "firework": "Pháo hoa",
        "firm": "Công ty, vững chắc", "firmly": "Một cách vững chắc", "first": "Đầu tiên", "firstly": "Trước tiên", "fish": "Cá",
        "fishing": "Câu cá", "fit": "Phù hợp, khỏe mạnh", "fitness": "Sự cân đối", "five": "Năm", "fix": "Sửa chữa",
        "fixed": "Cố định", "fixture": "Đồ đạc cố định", "flag": "Cờ", "flame": "Ngọn lửa", "flash": "Đèn flash, lóe sáng",
        "flat": "Bằng phẳng, căn hộ", "flavour": "Hương vị", "flaw": "Thiếu sót", "flawed": "Có lỗi", "flee": "Bỏ chạy",
        "fleet": "Hạm đội", "flesh": "Thịt", "flexibility": "Tính linh hoạt", "flexible": "Linh hoạt", "flight": "Chuyến bay",
        "float": "Nổi", "flood": "Lũ lụt", "floor": "Sàn nhà", "flour": "Bột mì", "flourish": "Phát triển rực rỡ",
        "flow": "Dòng chảy", "flower": "Hoa", "flu": "Bệnh cúm", "fluid": "Chất lỏng", "fly": "Bay, con ruồi",
        "flying": "Sự bay", "focus": "Tập trung", "fold": "Gấp", "folding": "Gấp lại được", "folk": "Dân gian",
        "follow": "Theo sau", "following": "Theo sau", "fond": "Ưu thích", "food": "Thức ăn", "fool": "Kẻ ngốc",
        "foot": "Chân", "footage": "Cảnh quay", "football": "Bóng đá", "for": "Cho", "forbid": "Cấm",
        "force": "Lực lượng, bắt buộc", "forecast": "Dự báo", "foreign": "Nước ngoài", "foreigner": "Người nước ngoài", "forest": "Rừng",
        "forever": "Mãi mãi", "forge": "Rèn luyện, giả mạo", "forget": "Quên", "forgive": "Tha thứ", "fork": "Cái nĩa",
        "form": "Hình dạng, mẫu", "formal": "Trang trọng", "format": "Định dạng", "formation": "Sự hình thành", "former": "Trước đây",
        "formerly": "Trước đây", "formula": "Công thức", "formulate": "Đưa ra", "forth": "Phía trước", "forthcoming": "Sắp tới",
        "fortunate": "May mắn", "fortunately": "May mắn thay", "fortune": "Vận may, gia sản", "forty": "Bốn mươi", "forum": "Diễn đàn",
        "forward": "Phía trước", "fossil": "Hóa thạch", "foster": "Nuôi dưỡng", "found": "Thành lập, tìm thấy (V2)", "foundation": "Nền tảng",
        "founder": "Người sáng lập", "four": "Bốn", "fourteen": "Mười bốn", "fourth": "Thứ tư", "fraction": "Phân số",
        "fragile": "Mong manh", "fragment": "Mảnh vỡ", "frame": "Khung", "framework": "Khuôn khổ", "franchise": "Nhượng quyền",
        "frankly": "Thành thật mà nói", "fraud": "Gian lận", "free": "Miễn phí, tự do", "freedom": "Tự do", "freely": "Một cách tự do",
        "freeze": "Đóng băng", "frequency": "Tần suất", "frequent": "Thường xuyên", "frequently": "Thường xuyên", "fresh": "Tươi",
        "fridge": "Tủ lạnh", "friend": "Bạn bè", "friendly": "Thân thiện", "friendship": "Tình bạn", "frighten": "Làm sợ hãi",
        "frightened": "Hoảng sợ", "frightening": "Khủng khiếp", "frog": "Con ếch", "from": "Từ", "front": "Phía trước",
        "frozen": "Đóng băng", "fruit": "Trái cây", "frustrated": "Thất vọng, nản lòng", "frustrating": "Gây bực bội", "frustration": "Sự thất vọng",
        "fry": "Chiên, rán", "fuel": "Nhiên liệu", "fulfil": "Hoàn thành", "full": "Đầy", "full-time": "Toàn thời gian",
        "fully": "Đầy đủ", "fun": "Vui vẻ", "function": "Chức năng", "functional": "Thuộc chức năng", "fund": "Quỹ",
        "fundamental": "Cơ bản", "fundamentally": "Về cơ bản", "funding": "Kinh phí", "fundraising": "Gây quỹ", "funeral": "Đám tang",
        "funny": "Vui nhộn", "fur": "Lông thú", "furious": "Giận dữ", "furniture": "Nội thất", "further": "Xa hơn",
        "furthermore": "Hơn nữa", "future": "Tương lai",
        "epidemic": "Dịch bệnh", "episode": "Tập phim", "equal": "Công bằng, bằng nhau", "equality": "Sự bình đẳng", "equally": "Một cách bình đẳng",
        "equation": "Phương trình", "equip": "Trang bị", "equipment": "Thiết bị", "equivalent": "Tương đương", "era": "Kỷ nguyên",
        "erect": "Dựng lên", "erode": "Ăn mòn", "erosion": "Sự xói mòn", "error": "Lỗi", "erupt": "Phun trào",
        "escalate": "Leo thang", "escape": "Thoát khỏi", "especially": "Đặc biệt", "essay": "Bài tiểu luận", "essence": "Bản chất",
        "essential": "Thiết yếu", "essentially": "Về bản chất", "establish": "Thiết lập", "establishment": "Sự thiết lập", "estate": "Bất động sản",
        "estimate": "Ước tính", "estimation": "Sự ước tính", "eternal": "Vĩnh cửu", "ethic": "Đạo đức", "ethical": "Thuộc đạo đức",
        "ethics": "Đạo đức học", "ethnic": "Thuộc dân tộc", "euro": "Đồng Euro", "evacuate": "Sơ tán", "evaluate": "Đánh giá",
        "evaluation": "Sự đánh giá", "evaporate": "Bay hơi", "eve": "Đêm trước", "even": "Thậm chí, chẵn", "evening": "Buổi tối",
        "event": "Sự kiện", "eventual": "Cuối cùng", "eventually": "Cuối cùng", "ever": "Đã từng", "every": "Mỗi",
        "everybody": "Mọi người", "everyday": "Hàng ngày", "everyone": "Mọi người", "everything": "Mọi thứ", "everywhere": "Mọi nơi",
        "evict": "Đuổi đi", "evidence": "Bằng chứng", "evident": "Hiển nhiên", "evoke": "Gợi nhớ", "evolution": "Tiến hóa",
        "evolutionary": "Thuộc tiến hóa", "evolve": "Tiến hóa", "exacerbate": "Làm trầm trọng thêm", "exact": "Chính xác", "exactly": "Chính xác",
        "exaggerate": "Phóng đại", "exam": "Kỳ thi", "examination": "Kỳ thi, kiểm tra", "examine": "Kiểm tra", "example": "Ví dụ",
        "exasperate": "Làm bực tức", "exceed": "Vượt quá", "excellent": "Xuất sắc", "except": "Ngoại trừ", "exception": "Ngoại lệ",
        "exceptional": "Ngoại lệ, đặc biệt", "excess": "Sự dư thừa", "excessive": "Quá mức", "excessively": "Quá mức", "exchange": "Trao đổi",
        "excited": "Hào hứng", "excitement": "Sự hào hứng", "exciting": "Thú vị", "exclude": "Loại trừ", "exclusion": "Sự loại trừ",
        "exclusive": "Độc quyền", "exclusively": "Độc quyền", "excuse": "Lời xin lỗi, lý do", "execute": "Thi hành, hành hình", "execution": "Sự thực hiện",
        "executive": "Điều hành", "exemplify": "Minh họa", "exempt": "Miễn", "exercise": "Tập thể dục, bài tập", "exert": "Sử dụng sức lực",
        "exhale": "Thở ra", "exhaust": "Khí thải, làm mệt lử", "exhausted": "Kiệt sức", "exhausting": "Làm kiệt sức", "exhaustive": "Toàn diện",
        "exhibit": "Trưng bày", "exhibition": "Triển lãm", "exile": "Trực xuất, lưu đày", "exist": "Tồn tại", "existence": "Sự tồn tại",
        "exit": "Lối thoát", "exotic": "Kỳ lạ", "expand": "Mở rộng", "expansion": "Sự mở rộng", "expect": "Mong đợi",
        "expectancy": "Sự mong đợi", "expectation": "Kỳ vọng", "expedition": "Cuộc thám hiểm", "expel": "Trục xuất", "expenditure": "Chi phí",
        "expense": "Chi phí", "expensive": "Đắt tiền", "experience": "Kinh nghiệm", "experienced": "Có kinh nghiệm", "experiment": "Thí nghiệm",
        "experimental": "Thuộc thí nghiệm", "expert": "Chuyên gia", "expertise": "Chuyên môn", "expire": "Hết hạn", "explain": "Giải thích",
        "explanation": "Lời giải thích", "explicit": "Rõ ràng", "explicitly": "Một cách rõ ràng", "explode": "Nổ", "exploit": "Khai thác",
        "exploitation": "Sự khai thác", "exploration": "Sự thám hiểm", "explore": "Khám phá", "explosion": "Vụ nổ", "explosive": "Chất nổ",
        "export": "Xuất khẩu", "expose": "Tiếp xúc, phanh phui", "exposure": "Sự tiếp xúc", "express": "Bày tỏ", "expression": "Sự bày tỏ",
        "expressive": "Có sức diễn cảm", "exquisite": "Tinh tế", "extend": "Mở rộng", "extension": "Sự mở rộng", "extensive": "Rộng rãi",
        "extent": "Mức độ", "exterior": "Bên ngoài", "external": "Bên ngoài", "extra": "Thêm", "extract": "Chiết xuất",
        "extraordinary": "Phi thường", "extreme": "Cực đoan", "extremely": "Cực kỳ", "extremist": "Người cực đoan", "eye": "Mắt",
    }
    
    if word in mapping:
        return mapping[word]
    return "Cần cập nhật"

def main():
    filepath = "data/translated/oxford5000_vn.csv"
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        return

    df = pd.read_csv(filepath)
    print(f"Loaded {len(df)} rows.")

    # Fix the broken mapping
    df['meaning_vi'] = df.apply(lambda row: get_vietnamese_meaning(str(row['word']).lower(), row.get('type'), row.get('definition')), axis=1)

    df.to_csv(filepath, index=False)
    print("Fixed Oxford 5000 mapping for segments A-N (over 1000 words).")

if __name__ == "__main__":
    main()
